// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbdMB3TBrnz9JH2LDz4VaR53N4OuFZ_fw',
    appId: '1:196594758089:web:be3d5f3ba22039d809f818',
    messagingSenderId: '196594758089',
    projectId: 'finik-flutter-app',
    authDomain: 'finik-flutter-app.firebaseapp.com',
    storageBucket: 'finik-flutter-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxu95o4NtSE4h2OTKQlnL6PmN4aS4iUNg',
    appId: '1:196594758089:android:42ab650c26d1046e09f818',
    messagingSenderId: '196594758089',
    projectId: 'finik-flutter-app',
    storageBucket: 'finik-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8WeORcMHsWtSuI51crifwpqxcj4rwaPw',
    appId: '1:196594758089:ios:a87c32142157023a09f818',
    messagingSenderId: '196594758089',
    projectId: 'finik-flutter-app',
    storageBucket: 'finik-flutter-app.appspot.com',
    iosBundleId: 'com.example.finik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8WeORcMHsWtSuI51crifwpqxcj4rwaPw',
    appId: '1:196594758089:ios:99dbe34bba976f2509f818',
    messagingSenderId: '196594758089',
    projectId: 'finik-flutter-app',
    storageBucket: 'finik-flutter-app.appspot.com',
    iosBundleId: 'com.example.finik.RunnerTests',
  );
}
